---
- name: Provision PVE Managed Hosts
  hosts: prometheus
  become: yes
  gather_facts: yes


  # --------------------------------------------- #
  # INLINE VARS
  # --------------------------------------------- #
  vars:
    # roles to include
    __include_roles:
      - jchristianh.lab_setup.prometheus


  # --------------------------------------------- #
  # TASKS
  # --------------------------------------------- #
  tasks:
    - name: Include required variables for environment
      include_vars:
        dir: "vars/{{ __pve_env | default('tower_lab') }}"


    - name         : Provision environment
      include_role :
        name       : "{{ lv_provision }}"
      loop         : "{{ __include_roles }}"
      loop_control :
        loop_var   : lv_provision


...
